/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_dr_testappdemo_DR_JNITest */

#ifndef _Included_dr_dr_testappdemo_DR_JNITest
#define _Included_dr_dr_testappdemo_DR_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dr_dr_testappdemo_DR_JNITest
 * Method:    getSuccessKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dr_dr_1testappdemo_DR_1JNITest_getSuccessKey
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
